---
- name: Ensure Java 17 is installed
  package:
    name: java-17-openjdk
    state: present

- name: Set Java 17 as default
  shell: |
    alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk*/bin/java 2
    alternatives --set java /usr/lib/jvm/java-17-openjdk*/bin/java
  args:
    executable: /bin/bash

- name: Add Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present

- name: Install Jenkins
  package:
    name: jenkins
    state: present

- name: Create systemd override directory
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: 0755

- name: Override Jenkins ExecStart to use jenkins.war with Java 17
  copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/java -jar /usr/share/java/jenkins.war
  notify:
    - Reload systemd
    - Restart Jenkins

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    enabled: true
    state: started

- name: Wait for Jenkins to generate admin password
  wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
    timeout: 120

- name: Show Jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Print Jenkins admin password
  debug:
    msg: "🔐 Jenkins Initial Admin Password: {{ jenkins_password.stdout }}"
